# -*- coding: utf-8 -*-
"""Collect_nuforc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l4xHulhpSoHzoXjX0q2-Aijx6mNw8_JL

#### Desenvolva um script Python para executar a coleta de dados dos vinte anos, entre setembro 1997 e agosto de 2017. Coloque tudo em um DataFrame e depois salve em um arquivo .csv.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

"""#### Criando função"""

# adicionar sleep function between each iteration
def web_scraper(url, tupla):
  df = pd.DataFrame()
  for year_month in range(tupla[0], tupla[1]):
    month = str(year_month)[4:]
    if not month == '00' and int(month) <= 12:
      request = requests.get('{}{}.html'.format(url, str(year_month))).text
      soup = BeautifulSoup(request, 'html.parser')
      table = soup.find_all('table')[0]
      df_tmp = pd.read_html(str(table))[0]
      df = pd.concat([df, df_tmp],ignore_index=True)
      time.sleep(5)
  return df

"""#### Chamando função"""

df = web_scraper("http://www.nuforc.org/webreports/ndxe", (199709, 201709))
df.to_csv('ufoCollect.csv')